<?php
/**
 * BOSS Cloaker - Installation Script
 * Run this once to set up the database and create the admin account
 * DELETE THIS FILE AFTER INSTALLATION!
 */

$step = $_GET['step'] ?? 'check';
$error = '';
$success = '';

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $dbHost = $_POST['db_host'] ?? 'localhost';
    $dbPort = $_POST['db_port'] ?? '3306';
    $dbName = $_POST['db_name'] ?? 'boss_cloaker';
    $dbUser = $_POST['db_user'] ?? '';
    $dbPass = $_POST['db_pass'] ?? '';
    $adminPass = $_POST['admin_pass'] ?? '';
    
    try {
        // Test connection
        $dsn = "mysql:host=$dbHost;port=$dbPort;charset=utf8mb4";
        $pdo = new PDO($dsn, $dbUser, $dbPass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
        
        // Create database if not exists
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `$dbName`");
        
        // Run schema
        $schemaFile = __DIR__ . '/schema.sql';
        if (file_exists($schemaFile)) {
            $schema = file_get_contents($schemaFile);
            // Remove CREATE DATABASE and USE statements (we already did that)
            $schema = preg_replace('/CREATE DATABASE.*?;/s', '', $schema);
            $schema = preg_replace('/USE.*?;/s', '', $schema);
            
            // Execute each statement
            $statements = array_filter(array_map('trim', explode(';', $schema)));
            foreach ($statements as $stmt) {
                if (!empty($stmt)) {
                    $pdo->exec($stmt);
                }
            }
        }
        
        // Create admin user
        $hashedPassword = password_hash($adminPass ?: 'admin123', PASSWORD_BCRYPT, ['cost' => 12]);
        
        // Check if admin exists
        $check = $pdo->prepare("SELECT id FROM users WHERE username = 'admin'");
        $check->execute();
        if ($check->fetch()) {
            $pdo->prepare("UPDATE users SET password = ? WHERE username = 'admin'")
                ->execute([$hashedPassword]);
        } else {
            $pdo->prepare("INSERT INTO users (username, password, email) VALUES ('admin', ?, 'admin@boss.local')")
                ->execute([$hashedPassword]);
        }
        
        // Write config with actual DB values only — do NOT overwrite functions/session logic
        // Instead, write a .env-style config that the main config.php reads
        $envContent = "<?php\n";
        $envContent .= "// Auto-generated by install.php — database credentials\n";
        $envContent .= "// The main config.php reads these if env vars are not set\n";
        $envContent .= "putenv('DB_HOST=' . " . var_export($dbHost, true) . ");\n";
        $envContent .= "putenv('DB_PORT=' . " . var_export($dbPort, true) . ");\n";
        $envContent .= "putenv('DB_NAME=' . " . var_export($dbName, true) . ");\n";
        $envContent .= "putenv('DB_USER=' . " . var_export($dbUser, true) . ");\n";
        $envContent .= "putenv('DB_PASS=' . " . var_export($dbPass, true) . ");\n";
        $envContent .= "putenv('SESSION_SECRET=' . " . var_export(bin2hex(random_bytes(32)), true) . ");\n";
        
        file_put_contents(__DIR__ . '/api/db_config.php', $envContent);
        
        $success = 'Kurulum başarılı! Admin kullanıcı adı: admin, Şifre: ' . ($adminPass ?: 'admin123');
        $step = 'done';
        
    } catch (PDOException $e) {
        $error = 'Veritabanı hatası: ' . $e->getMessage();
    } catch (Exception $e) {
        $error = 'Hata: ' . $e->getMessage();
    }
}

// Check requirements
$checks = [
    'PHP 7.4+' => version_compare(PHP_VERSION, '7.4.0', '>='),
    'PDO MySQL' => extension_loaded('pdo_mysql'),
    'JSON' => extension_loaded('json'),
    'OpenSSL' => extension_loaded('openssl'),
    'Session' => extension_loaded('session'),
    'mod_rewrite' => function_exists('apache_get_modules') ? in_array('mod_rewrite', apache_get_modules()) : true,
    'config.php yazılabilir' => is_writable(__DIR__ . '/api/'),
];
?>
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BOSS Cloaker - Kurulum</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: system-ui, -apple-system, sans-serif; background: #09090b; color: #fafafa; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 2rem; }
        .container { max-width: 600px; width: 100%; }
        .card { background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 2rem; }
        h1 { font-size: 1.5rem; margin-bottom: 0.5rem; color: #10b981; }
        h2 { font-size: 1.2rem; margin-bottom: 1rem; }
        p { color: #a1a1aa; font-size: 0.875rem; margin-bottom: 1rem; }
        .check { display: flex; justify-content: space-between; padding: 0.5rem 0; border-bottom: 1px solid rgba(255,255,255,0.05); }
        .check .ok { color: #10b981; }
        .check .fail { color: #ef4444; }
        label { display: block; font-size: 0.875rem; color: #a1a1aa; margin-bottom: 0.25rem; margin-top: 0.75rem; }
        input { width: 100%; padding: 0.625rem; background: rgba(0,0,0,0.3); border: 1px solid rgba(255,255,255,0.1); border-radius: 6px; color: #fafafa; font-family: monospace; font-size: 0.875rem; }
        input:focus { outline: none; border-color: #10b981; }
        button { width: 100%; padding: 0.75rem; background: #10b981; color: #000; border: none; border-radius: 6px; font-weight: 600; font-size: 1rem; cursor: pointer; margin-top: 1.5rem; }
        button:hover { background: #059669; }
        .error { background: rgba(239,68,68,0.1); border: 1px solid rgba(239,68,68,0.3); color: #ef4444; padding: 0.75rem; border-radius: 6px; margin-bottom: 1rem; font-size: 0.875rem; }
        .success { background: rgba(16,185,129,0.1); border: 1px solid rgba(16,185,129,0.3); color: #10b981; padding: 0.75rem; border-radius: 6px; margin-bottom: 1rem; font-size: 0.875rem; }
        .warning { background: rgba(245,158,11,0.1); border: 1px solid rgba(245,158,11,0.3); color: #f59e0b; padding: 0.75rem; border-radius: 6px; margin-top: 1rem; font-size: 0.875rem; }
        .logo { text-align: center; margin-bottom: 2rem; }
        .logo span { font-size: 2rem; font-weight: 800; letter-spacing: -1px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo">
            <span style="color:#10b981">BOSS</span> <span>CLOAKER</span>
            <p style="margin-top:0.5rem">PHP/Plesk Kurulum Sihirbazı</p>
        </div>
        
        <div class="card">
            <?php if ($error): ?>
                <div class="error"><?= htmlspecialchars($error) ?></div>
            <?php endif; ?>
            
            <?php if ($step === 'done'): ?>
                <div class="success"><?= htmlspecialchars($success) ?></div>
                <h2>Kurulum Tamamlandı!</h2>
                <p>Artık admin paneline giriş yapabilirsiniz.</p>
                <a href="/login"><button type="button">Admin Paneline Git</button></a>
                <div class="warning">
                    <strong>⚠️ GÜVENLİK:</strong> Bu dosyayı (install.php) sunucudan SİLİN!
                </div>
            <?php elseif ($step === 'check'): ?>
                <h2>Sistem Gereksinimleri</h2>
                <?php foreach ($checks as $name => $ok): ?>
                    <div class="check">
                        <span><?= $name ?></span>
                        <span class="<?= $ok ? 'ok' : 'fail' ?>"><?= $ok ? '✓' : '✗' ?></span>
                    </div>
                <?php endforeach; ?>
                
                <?php if (array_product($checks)): ?>
                    <p style="color:#10b981; margin-top:1rem">Tüm gereksinimler karşılanıyor!</p>
                    <a href="?step=install"><button type="button">Kuruluma Başla →</button></a>
                <?php else: ?>
                    <p style="color:#ef4444; margin-top:1rem">Bazı gereksinimler karşılanmıyor. Lütfen düzeltin.</p>
                <?php endif; ?>
            <?php else: ?>
                <h2>Veritabanı ve Admin Ayarları</h2>
                <form method="POST">
                    <label>MySQL Host</label>
                    <input type="text" name="db_host" value="localhost" required>
                    
                    <label>MySQL Port</label>
                    <input type="text" name="db_port" value="3306" required>
                    
                    <label>Veritabanı Adı</label>
                    <input type="text" name="db_name" value="boss_cloaker" required>
                    
                    <label>MySQL Kullanıcı</label>
                    <input type="text" name="db_user" value="" required placeholder="root">
                    
                    <label>MySQL Şifre</label>
                    <input type="password" name="db_pass" value="" placeholder="Veritabanı şifresi">
                    
                    <label>Admin Şifre</label>
                    <input type="password" name="admin_pass" value="" required placeholder="Güçlü bir şifre girin">
                    
                    <button type="submit">Kurulumu Tamamla</button>
                </form>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
